require("core.plugin_config.vimtex")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-lint")
-- require("core.plugin_config.obsidian-nvim")
require("core.plugin_config.telescope")
--require("core.plugin_config.cmp")
--require("core.plugin_config.nvim-treesitter")
--require("core.plugin_config.vim-prettier")
require("core.plugin_config.pomo")
