#!bin/bash

export OS=$(uname -s)
export LINUX="Linux"
export MAC="Darwin"

mkdir -p ${HOME}/Software

# Install Homebrew if MacOS
if [ "$OS" = "$MAC" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install zoxide, fzf, ripgrep, neovim, stow
cd ${HOME}/Software
case $OS in
    $LINUX)
        # update/upgrade
        sudo apt update
        sudo apt upgrade -y
        # sudo apt install -y zoxide fzf ripgrep neovim
        curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
        sudo apt install -y fzf ripgrep neovim python3-neovim stow
        ;;
    $MAC)
        /opt/homebrew/bin/brew install zoxide fzf ripgrep neovim stow
        ;;
esac

# Check if git is installed
# Install git if not installed
if ! command -v git &> /dev/null; then
    case $OS in
        $LINUX)
            sudo apt install -y git-all
            ;;
        $MAC)
            /opt/homebrew/bin/brew install git
            ;;
    esac
fi

# Clone dotfiles repo
# git clone https://github.com/homeomorfismo/dotfiles.git ${HOME}/dotfiles

# Install dotfiles
cd ${HOME}/dotfiles
stow -t ${HOME} -v ${HOME}/dotfiles

# Check if ngsolve, mfem, petsc, slepc are installed
# Install them if not installed by calling the respective scripts
echo "Checking standard software installation..."
if [ -d "${HOME}/Software/ngs" ]; then
    echo "ngsolve is already installed"
else
    echo "Installing ngsolve..."
    bash ${HOME}/dotfiles/scripts/install_ngsolve.sh
fi

if [ -d "${HOME}/Software/mfem" ]; then
    echo "mfem is already installed"
else
    echo "Installing mfem..."
    bash ${HOME}/dotfiles/scripts/install_mfem.sh
fi

if [ -d "${HOME}/Software/petsc" ]; then
    echo "petsc is already installed"
else
    echo "Installing petsc..."
    bash ${HOME}/dotfiles/scripts/install_petsc.sh
fi

if [ -d "${HOME}/Software/slepc" ]; then
    echo "slepc is already installed"
else
    echo "Installing slepc..."
    bash ${HOME}/dotfiles/scripts/install_slepc.sh
fi

echo "Installation complete!"
